config/routes.rb
Rails.application.routes.draw do
  get 'payment/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :listings do
    resources :bookings
    resources :payment
  end
  
  resources :users do
  resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  post "/listings/:id/verify" => "listings#verify", as: "verify"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'
  post 'payment/checkout'
  post '/search' => "listings#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Clearance.configure do |config|
  config.routes = false
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	paginates_per 10

	scope :listing_name, -> (listing_name) { where("name ILIKE ?" , "%#{listing_name}%")   }
    scope :descrip, -> (description) { where("description ILIKE ?", "%#{description}%" ) }
	scope :price, -> (min_price, max_price) { where("price BETWEEN ? and ?", min_price, max_price ) }
	
	def self.search_city(query)
		where("name ILIKE :name", name: "%#{query}%").map do |record|
		  record.name 
		end
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	def index
		@listings = Listing.page(params[:page])
		@listings = @listings.listing_name(params[:listing_name].strip).page(params[:page]).order('created_at DESC') if params[:listing_name].present?
		@listings = @listings.descrip(params[:description].strip).page(params[:page]).order('created_at DESC') if params[:description].present?
	
		if params[:min_price].present? && params[:max_price].present?
			@listings = @listings.price(params[:min_price], params[:max_price]).page(params[:page]).order('created_at DESC') 
		elsif params[:min_price].present?
			@listings = @listings.where("price > #{params[:min_price]}").page(params[:page]).order('created_at DESC')
		elsif params[:max_price].present?
			@listings = @listings.where("price < #{params[:max_price]}").page(params[:page]).order('created_at DESC')    
		elsif params[:tag]
		  @listings = Listing.tagged_with(params[:tag].titleize).paginate(:page => params[:page])
		end

	end

	def new
		@listing = Listing.new
	end

	def create
		listing = Listing.new(listing_params)
		listing.user_id = current_user.id
		if listing.save
			flash[:message] = "Saved!"
			@listing = Listing.find(params[:listing_id])
			ReservationMailer.booking_email(current_user,listing.user_id,listing).deliver_now
			redirect_to listings_path
		else
			flash[:message] = "Try again."
			redirect_to listings_path
		end
	end

	def show
		@listing = Listing.find(params[:id])
		@user = User.find(@listing.user_id)
	end

	def edit
		@lisintg = Listing.find(params[:id])
	end

	def update
	end

	def destroy
		@listing = Listing.find(params[:id]).delete
		redirect_to listings_path
	end

	def verify
		listing = Listing.find(params[:id])

		if listing.verified?
			listing.update(verified: false)
			flash[:message] = "It has been unverified."
		else
			# listing.verify = 'true'
			listing.update(verified: true)
			flash[:message] = "It has been verified."
		end
			redirect_to listing_path
	end

	def search
		@name = Listing.search_city(params["query"])
		@listings = Listing.all
		# byebug
		respond_to do |format|
		  format.json { render json: @listings }
		  format.js # remote: true is sent a js format and sends you to search.js.erb
		end
	end

	private
	def listing_params
		params.require(:listing).permit(
			:name,
			:description,
			:place_type,
			:property_type,
			:room_number,
			:bed_number,
			:guest_number,
			:address,
			:city,
			:state,
			:country,
			:zipcode,
			:price
			)
	end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name%>
</div>

<div class="text-field">
  <%= form.label :description %>
  <%= form.text_field :description%>
</div>

<div class="text-field">
  <%= form.label :place_type %>
  <%= form.text_field :place_type%>
</div>

<div class="text-field">
  <%= form.label :property_type %>
  <%= form.text_field :property_type%>
</div>

<div class="text-field">
  <%= form.label :room_number %>
  <%= form.text_field :room_number%>
</div>

<div class="text-field">
  <%= form.label :bed_number %>
  <%= form.text_field :bed_number%>
</div>

<div class="text-field">
  <%= form.label :guest_number %>
  <%= form.text_field :guest_number%>
</div>

<div class="text-field">
  <%= form.label :address %>
  <%= form.text_field :address%>
</div>

<div class="text-field">
  <%= form.label :city %>
  <%= form.text_field :city%>
</div>

<div class="text-field">
  <%= form.label :state %>
  <%= form.text_field :state%>
</div>

<div class="text-field">
  <%= form.label :country %>
  <%= form.text_field :country%>
</div>

<div class="text-field">
  <%= form.label :zipcode %>
  <%= form.text_field :zipcode%>
</div>

<div class="text-field">
  <%= form.label :price%>
  <%= form.text_field :price%>
</div>

<div class="submit-field">
    <%= form.submit %>
</div>

app/views/listings/_search.html.erb
<div class="form mb-3">
    <div class="form-inline mb-3">    	
        <%= search.text_field :listing_name, placeholder: "Listing Name",id: 'listing-search', class: "form-control mr-4", list: "list" %>
        <%= search.text_field :description, placeholder: "Any text in description", class: "form-control mr-4", list: "description-list"  %>
	    <%= search.label :price_range %>
	    <%= search.text_field :min_price, placeholder: "Min Price" , class: "form-control mr-2" %>
	    to
	    <%= search.text_field :max_price, placeholder: "Max Price", class: "form-control mr-2"  %>
    </div>
    <%= search.submit "Search", class: "btn btn-outline-success" %>
</div>

app/views/listings/edit.html.erb
<h1> Edit Listing </h1>

<%= form_with model: @listing, local: true do |form| %>
	<%= render partial: '/listings/form', object: form %>
<% end %>

app/views/listings/index.html.erb
<p>
	<% if signed_in? %>
		<%= link_to "Add a property", new_listing_path %>
	<% end %>
</p>

<h4>Search Listings</h4>
<%= form_with model: @listing, method: :get, id: "search-form", local: true do |f| %>
	<%= render partial: '/listings/search', object: f %>
	<datalist id="list"></datalist>
	<datalist id="description-list"></datalist>
<% end %>

<%= paginate @listings %>

<% @listings.each do |listing| %>

<%= link_to listing.name, listing_path(listing.id) %><br>
<%= listing.description %><br>
<%= listing.place_type %><br>
<%= listing.property_type %><br>
<br>

<% end %>

<%= paginate @listings %>

app/views/listings/new.html.erb
<h2>New Listing!</h2>

<div>
    <%= form_with model: @listing, scope: :listing, local: true do |f| %>

        <%= render partial: '/listings/form', object: form %>
    <% end %>
</div>

app/views/listings/search.js.erb
$("#list").html();
<% @listing.each do |name| %>
  var option = document.createElement("option");
  option.value = "<%= name %>";

  //append option to list
  $("#list").append(option);
<% end %>

app/views/listings/show.html.erb
<h1> Listing </h1>

<% if @listing.verified? %>
This listing has been verified. <br>
<% end %>

ID| <%= @listing.id %> <br>
Name| <%= @listing.name %> <br>
Description|  <%= @listing.description %> <br>
Place Type| <%= @listing.place_type %> <br>
Property Type| <%= @listing.property_type %> <br>
No. of Rooms| <%= @listing.room_number %> <br>
No. of Beds| <%= @listing.bed_number %> <br>
No. of Guest|  <%= @listing.guest_number %> <br>
Price| <%= @listing.price %><br>
Created By| <%= "#{@user.first_name} #{@user.last_name}" %> <br>
Created On| <%= @listing.created_at.localtime %> <br>

Calendar (TBC) <br>
Book this Property (TBC) <br>

<% if @listing.user_id == current_user.id && signed_in? %>
    <%= link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-secondary outline" %>
    <%= link_to "Delete", listing_path(@listing.id), method: :delete, class: "btn btn-secondary outline" %>
<% elsif current_user.customer? %>
    <%= link_to "Book It!", new_listing_booking_path(@listing.id), class: "btn btn-success" %>

<% end %>

<% if current_user.moderator? %>
	<%= button_to "Verify", verify_path, class: "btn btn-success" %>
<% end %>