config/routes.rb
Rails.application.routes.draw do
  get 'payment/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :listings do
    resources :bookings
    resources :payment
  end
  
  resources :users do
  resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  post "/listings/:id/verify" => "listings#verify", as: "verify"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'
  post 'payment/checkout'
  post '/search' => "listings#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Clearance.configure do |config|
  config.routes = false
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  def new
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
     :amount => "10.00", #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )
  
    if result.success?
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/payment/new.html.erb
<h1>Payment#new</h1>
<p>Find me in app/views/payment/new.html.erb</p>
<div class="demo-frame">

<div class="demo-frame">

  <%= form_for :checkout_form, url: payment_checkout_path, html: { id: "cardForm" } do |form| %>

		<%= form.label :card_number, "Credit Card Number", html: {class: "hoster-fields--label"} %>
		<div id="card-number" class="hosted-field"></div>

		<%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
		<div id="expiration-date" class="hosted-field"></div>

		<%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
		<div id="cvv" class="hosted-field"></div>

		<%= form.hidden_field "payment_method_nonce" %>

		<div class="button-container">
			<%= form.submit "Purchase", disabled: true, class: "button button--green", id: "submit-payment-btn" %>
		</div>
  <%end%>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});

</script>