config/routes.rb
Rails.application.routes.draw do
  get 'payment/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :listings do
    resources :bookings
    resources :payment
  end
  
  resources :users do
  resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  post "/listings/:id/verify" => "listings#verify", as: "verify"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'
  post 'payment/checkout'
  post '/search' => "listings#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Clearance.configure do |config|
  config.routes = false
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if signed_in?
			@name = "#{current_user.first_name} #{current_user.last_name}"
			@role = "#{current_user.role}"
		else
			@name = "Guest"
		end
	end
end

app/views/welcome/index.html.erb
<p class="text-center h3 mb-3 font-weight-light">Welcome to a simple clone of AirBnB!</p>
<p class="text-center h6 mb-3 font-weight-light">What do you want to book today, <%= @name %> </p>

<% if signed_in? %>
<p class="text-center h6 mb-3 font-weight-light">Your access level is: <%= @role %> </p>

	<%= link_to "View your properties", listings_path %>
	<%= link_to "Add a property", new_listing_path %>

<% end %>