config/routes.rb
Rails.application.routes.draw do
  get 'payment/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :listings do
    resources :bookings
    resources :payment
  end
  
  resources :users do
  resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  post "/listings/:id/verify" => "listings#verify", as: "verify"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'
  post 'payment/checkout'
  post '/search' => "listings#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Clearance.configure do |config|
  config.routes = false
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<script
			  src="https://code.jquery.com/jquery-3.3.1.js"
			  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
			  crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="../../assets/stylesheets/application.css">
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= link_to ("Home"), root_path, class:'btn btn-primary' %>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete, class:'btn btn-danger' %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path, class: 'btn btn-primary' %>
    <% end -%>
  </div>



  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>
  <%= yield %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>